all:
  hosts:
    master-node01:
      ansible_host: 10.202.0.2
      ip: 10.202.0.2
      access_ip: 10.202.0.2
    worker-node01:
      ansible_host: 10.202.0.3
      ip: 10.202.0.3
      access_ip: 10.202.0.3
  children:
    kube_control_plane:
      hosts:
        master-node01:
    kube_node:
      hosts:
        worker-node01:
    etcd:
      hosts:
        master-node01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
